jobs:

- job: BuildLinuxbrewCoreBottles
  timeoutInMinutes: 360

  pool:
    vmImage: 'ubuntu-16.04'

  container:
    image: linuxbrew/brew:latest

  steps:
  - script: printenv
    displayName: Azure printenv

  - bash: |
      mkdir -p /tmp/bottles
      cd /tmp/bottles
      umask 022
    displayName: Setup /tmp/bottles
  - bash: |
      git config --global user.name LinuxbrewTestBot
      git config --global user.email testbot@linuxbrew.sh
      cd /home/linuxbrew/.linuxbrew/Homebrew
      sudo git fetch origin --tags
      sudo git reset --hard origin/master
    displayName: Setup Homebrew
  - bash: |
      sudo rm -rf /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core
      sudo cp -a $(Build.Repository.LocalPath) /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core
    displayName: Copy homebrew-core
  - bash: |
      sudo /home/linuxbrew/.linuxbrew/bin/brew tap linuxbrew/extra
      sudo /home/linuxbrew/.linuxbrew/bin/brew tap linuxbrew/xorg
      sudo /home/linuxbrew/.linuxbrew/bin/brew tap homebrew/homebrew-test-bot
      cd /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core
      git checkout -b test
      git fetch origin "master:master" "pull/$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER/head:pr"
      git checkout pr
    displayName: Setup taps and checkout
  - bash: |
      cd /tmp/bottles
      sudo -E /home/linuxbrew/.linuxbrew/bin/brew test-bot --tap=homebrew/core --bintray-org=linuxbrew --git-name=LinuxbrewTestBot --git-email=testbot@linuxbrew.sh --keep-old --skip-recursive-dependents
      cp *.bottle.* $(Build.ArtifactStagingDirectory)
    displayName: Run test bot and copy json & bottle files
    env:
      HOMEBREW_DEVELOPER: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_VERBOSE: 1
      HOMEBREW_VERBOSE_USING_DOTS: 1
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: bottle-linux
      targetPath: $(Build.ArtifactStagingDirectory)
    displayName: Publish bottle-linux
